# Generated by Django 5.2.6 on 2025-09-17 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_providers',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_deal_id', models.CharField(max_length=100)),
                ('deal_name', models.CharField(max_length=255)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deal_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crm_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_synch.crmprovider')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crm_file_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('docx', 'Word Document'), ('xls', 'Excel'), ('xlsx', 'Excel Document'), ('jpg', 'JPEG Image'), ('png', 'PNG Image'), ('txt', 'Text File'), ('other', 'Other')], max_length=10)),
                ('file_url', models.URLField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_synch.deal')),
            ],
            options={
                'db_table': 'file_metadata',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_synch.crmprovider')),
                ('file_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_synch.filemetadata')),
            ],
            options={
                'db_table': 'sync_logs',
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['crm_provider', 'crm_deal_id'], name='deals_crm_pro_066ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_name'], name='deals_deal_na_e1f908_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('crm_provider', 'crm_deal_id')},
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['file_type'], name='file_metada_file_ty_7c102c_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['sync_status'], name='file_metada_sync_st_ee70ab_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['sync_timestamp'], name='file_metada_sync_ti_0165e1_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['deal', 'crm_file_id'], name='file_metada_deal_id_5fb042_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['file_name'], name='file_metada_file_na_a56e81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filemetadata',
            unique_together={('deal', 'crm_file_id')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['crm_provider', 'created_at'], name='sync_logs_crm_pro_cc6106_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['level'], name='sync_logs_level_91bf52_idx'),
        ),
    ]
